# Generated by Django 5.1.6 on 2025-03-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/images",
                verbose_name="Изображение",
            ),
        ),
    ]
