# Generated by Django 5.1.6 on 2025-03-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="names",
            field=models.CharField(max_length=100, verbose_name="Наименование"),
        ),
    ]
