# Generated by Django 5.1.6 on 2025-03-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_is_available_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["names", "category"],
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("remove_any_product", "Remove any product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
